_target_: berlin_lst_downscaling.modules.LSTDownscalingModule

defaults:
  - network: unet

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-3
  weight_decay: 1.0e-5

scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    mode: min
    factor: 0.5
    patience: 10
