model:
  _target_: berlin_lst_downscaling.models.UNet2D
  in_channels: 5
  hidden_channels: [64, 128, 256, 512]
  out_channels: 1
  depth: 4

loss:
  _target_: torch.nn.L1Loss

metrics:
  mae:
    _target_: torchmetrics.MeanAbsoluteError
  rmse:
    _target_: torchmetrics.MeanSquaredError
    squared: false
