model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}-{val/loss:.4f}"
  monitor: "val/loss"
  save_top_k: 3
  mode: min

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val/loss"
  patience: 20
  mode: min

model_summary:
  _target_: lightning.pytorch.callbacks.ModelSummary
  max_depth: 3
